server:
  host: "0.0.0.0"
  port: 8000

instagram_accounts:
  - username: "account1"
    password: "password1"
    sessionid_file: "./sessions/sessionid_account1.txt"
    use_proxy: false
    proxy: null

  - username: "account2"
    password: "password2"
    sessionid_file: "./sessions/sessionid_account2.txt"
    use_proxy: true
    proxy: "http://user:pass@1.2.3.4:8080"

poller:
  poll_interval_seconds: 30
  random_delay_min_ms: 8000
  random_delay_max_ms: 15000

throttle:
  per_user_cooldown_seconds: 3600
  global_hourly_limit: 100

security:
  webhook_verify_token: "change-me"
